name: pdf_viewer_jk
description: A flutter plugin for viewing PDF files in mobile app (Android & iOS).
version: 1.2.0
repository: https://github.com/jawadsahil/pdf_viewer_jk
homepage: http://jawad.pro

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  async: ^2.5.0
  flutter_cache_manager: ^2.1.1
  path_provider: ^1.6.27
  numberpicker: ^1.3.0
  http: ^0.12.2
  path: ^1.7.0
  flutter_svg: ^0.19.3
  pool: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: pro.jawad.pdf_viewer_jk
        pluginClass: PdfViewerJkPlugin
      ios:
        pluginClass: PdfViewerJkPlugin
